vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: '%article_attachments%'
            upload_destination: '%kernel.project_dir%/public%article_attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false



